//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Atencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Atencion()
        {
            this.Tb_Receta = new HashSet<Tb_Receta>();
        }
    
        public string cod_ate { get; set; }
        public string cod_med { get; set; }
        public string comen_ate { get; set; }
        public string est_ate { get; set; }
        public string num_sala { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string cod_suc { get; set; }
        public string cod_pac { get; set; }
    
        public virtual Tb_Medico Tb_Medico { get; set; }
        public virtual Tb_Sucursal Tb_Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Receta> Tb_Receta { get; set; }
        public virtual Tb_Paciente Tb_Paciente { get; set; }
    }
}
