//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detalle_Receta
    {
        public string cod_rec { get; set; }
        public string cod_medi { get; set; }
        public string cant_medi { get; set; }
        public string indicaciones { get; set; }
    
        public virtual Tb_Medicamento Tb_Medicamento { get; set; }
        public virtual Tb_Receta Tb_Receta { get; set; }
    }
}
