//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Paciente()
        {
            this.Tb_Atencion = new HashSet<Tb_Atencion>();
        }
    
        public string cod_pac { get; set; }
        public string nom_pac { get; set; }
        public string ape_pac { get; set; }
        public string genero { get; set; }
        public byte[] foto { get; set; }
        public string telf { get; set; }
        public string comen_pac { get; set; }
        public string dir_pac { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fech_nac_pac { get; set; }
        public string sangre { get; set; }
        public string cod_seg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string est_pac { get; set; }
        public string cod_ubigeo { get; set; }
        public string dni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Atencion> Tb_Atencion { get; set; }
        public virtual Tb_Seguro Tb_Seguro { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo1 { get; set; }
    }
}
