//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Sucursal()
        {
            this.Tb_Atencion = new HashSet<Tb_Atencion>();
        }
    
        public string cod_suc { get; set; }
        public string nom_suc { get; set; }
        public string dir_suc { get; set; }
        public string telf_suc { get; set; }
        public string cod_ubigeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Atencion> Tb_Atencion { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
    }
}
